config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :user_roles
    resources :o_auths
    resources :abilities
    resources :roles
    resources :recipes
    resources :recipe_ingredients
    resources :ingredients
    resources :places

    root to: 'users#index'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Comment out before initializing
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  # user root
  resource :user, only: %i[show edit]
  root 'welcome#index'

  # about recipes
  resources :ingredients
end

app/models/ability.rb
# frozen_string_literal: true

# Ability of Role
# Not used now
class Ability < ApplicationRecord
  has_many :role_ability
  has_many :roles, through: :role_ability
end

app/models/application_record.rb
# frozen_string_literal: true

# Whats?
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
# frozen_string_literal: true

# Ingredients for recipe
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients

  validates :name, presence: true, length: { maximum: 10 }, uniqueness: { case_sensitive: false }
end

app/models/o_auth.rb
# frozen_string_literal: true

# Authorization for user
class OAuth < ApplicationRecord
  belongs_to :user

  validates_presence_of :uid, :provider, :token
  validates_uniqueness_of :uid, scope: :provider
  validates :provider, inclusion: { in: %w[github facebook google] }
end

app/models/place.rb
# frozen_string_literal: true

# Place can mount under each place
class Place < ApplicationRecord
  has_many :children, class_name: 'Place', foreign_key: :parent_id, dependent: :delete_all
  belongs_to :parent, class_name: 'Place', optional: true, foreign_key: :parent_id
end

app/models/recipe.rb
# frozen_string_literal: true

# Recipe
class Recipe < ApplicationRecord
  # Roles
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients

  validates :name, presence: true, length: { maximum: 10 }, uniqueness: { case_sensitive: false }
end

app/models/recipe_ingredient.rb
# frozen_string_literal: true

# Recipe-Ingredient
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/role.rb
# frozen_string_literal: true

# Role of Users
class Role < ApplicationRecord
  validates :name, presence: true, length: { maximum: 10 },
                   uniqueness: { case_sensitive: false }
  # #User
  has_many :user_roles, dependent: :destroy
  has_many :users, through: :user_roles
  # #Ability
  has_many :role_ability, dependent: :destroy
  has_many :abilities, through: :role_ability
end

app/models/role_ability.rb
# frozen_string_literal: true

# :nodoc:
class RoleAbility < ApplicationRecord
  belongs_to :role
  belongs_to :ability
end

app/models/user.rb
# frozen_string_literal: true

# User Base Model
class User < ApplicationRecord
  # Authentication
  # Devise, #OAuth model
  include User::DeviseAndAuth
  # Authorization
  # Pundit, #Role and #Ability model
  include User::RoleAndAbility

  # name validates
  validates :first_name, presence: true, length: { maximum: 10 }, uniqueness: { case_sensitive: false }
  validates :last_name, presence: true, length: { maximum: 10 }, uniqueness: { case_sensitive: false }
end

app/models/user_role.rb
# frozen_string_literal: true

# User-Role
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

# Controller for recipe
class RecipesController < ApplicationController
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# index page for login user
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show; end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

# Index home page controller
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Helper for Application
module ApplicationHelper
  include SideBarHelper
  include FormWithBabelHelper
end

app/helpers/ingredients_helper.rb
# frozen_string_literal: true

# Helper for ingredient
module IngredientsHelper
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

# Helper for Recipe view
module RecipesHelper
end

app/helpers/side_bar_helper.rb
# frozen_string_literal: true

# Menu
module SideBarHelper
  def current_user_name
    current_user.try(:first_name) || 'USER'
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# helper of User
module UsersHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

# Helper for index
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <section class="section">
    <div class="container">
      <div class="columns is-multiline">
        <div class="column is-one-third">
          <article class="notification media has-background-white">
            <figure class="media-left">
            <span class="icon">
              <i class="has-text-warning fas fa-columns fa-lg"></i>
            </span>
            </figure>
            <div class="media-content">
              <div class="content">
                <h1 class="title is-size-4">Columns</h1>
                <p class="is-size-5 subtitle">
                  The power of <strong>Flexbox</strong> in a simple interface
                </p>
              </div>
            </div>
          </article>
        </div>
        <div class="column is-one-third">
          <article class="notification has-background-white media">
            <figure class="media-left">
            <span class="icon has-text-info">
              <i class="fab fa-lg fa-wpforms"></i>
            </span>
            </figure>
            <div class="media-content">
              <div class="content">
                <h1 class="title is-size-4">Form</h1>
                <p class="is-size-5 subtitle">
                  The indispensable <strong>form controls</strong>, designed for maximum clarity
                </p>
              </div>
            </div>
          </article>
        </div>
        <div class="column is-one-third">
          <article class="notification has-background-white media">
            <figure class="media-left">
            <span class="icon has-text-danger">
              <i class="fas fa-lg fa-cubes"></i>
            </span>
            </figure>
            <div class="media-content">
              <div class="content">
                <h1 class="title is-size-4">Components</h1>
                <p class="is-size-5 subtitle">
                  Advanced multi-part components with lots of possibilities
                </p>
              </div>
            </div>
          </article>
        </div>
        <div class="column is-one-third">
          <article class="notification has-background-white media">
            <figure class="media-left">
            <span class="icon has-text-grey">
              <i class="fas fa-lg fa-cogs"></i>
            </span>
            </figure>
            <div class="media-content">
              <div class="content">
                <h1 class="title is-size-4">Modifiers</h1>
                <p class="is-size-5 subtitle">
                  An <strong>easy-to-read</strong> naming system designed for humans
                </p>
              </div>
            </div>
          </article>
        </div>
        <div class="column is-one-third">
          <article class="notification has-background-white media">
            <figure class="media-left">
            <span class="icon has-text-primary">
              <i class="fas fa-lg fa-warehouse"></i>
            </span>
            </figure>
            <div class="media-content">
              <div class="content">
                <h1 class="title is-size-4">Layout</h1>
                <p class="is-size-5 subtitle">
                  Design the <strong>structure</strong> of your webpage with these CSS classes
                </p>
              </div>
            </div>
          </article>
        </div>
        <div class="column is-one-third">
          <article class="notification has-background-white media">
            <figure class="media-left">
            <span class="icon has-text-danger">
              <i class="fas fa-lg fa-cube"></i>
            </span>
            </figure>
            <div class="media-content">
              <div class="content">
                <h1 class="title is-size-4">Elements</h1>
                <p class="is-size-5 subtitle">
                  Essential interface elements that only require a <strong>single CSS class</strong>
                </p>
              </div>
            </div>
          </article>
        </div>
      </div>
    </div>
  </section>
  <hr>
  <div class="columns is-mobile is-centered">
    <div class="field is-grouped is-grouped-multiline">
      <div class="control">
        <div class="tags has-addons"><a class="tag is-link" href="https://github.com/dansup/bulma-templates">Bulma Templates</a>
          <span class="tag is-info">MIT license</span>
        </div>
      </div>
      <div class="control">
        <div class="tags has-addons ">
          <a class="tag is-dark" href="https://bulmatemplates.github.io/bulma-templates/templates/cheatsheet.html">
            use Bulma cheatsheet
          </a>
        </div>
      </div>
    </div>
  </div>

</footer>

app/views/layouts/_header.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <div class="columns">
      <div class="column is-12">
        <div class="container content">
          <i class="is-large fab fa-discord"></i>
          <i class="is-large fas fa-code"></i>
          <h1 class="title">61st <em>R</em> youri kyoku</h1>
          <h2 class="subtitle">
            料理作らないかい?
          </h2>
          <a href="https://github.com/kkiyama117/Hinatan" target="_blank" class="button is-primary is-large">
                <span class="icon">
                  <i class="fab fa-github"></i>
                </span>
            <span>Github</span>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render 'layouts/header/notice_and_alert' %>

app/views/layouts/_side_menu.html.erb
<div class="column is-3">
  <aside class="is-medium menu">
    <p class="menu-label">
      Features
    </p>
    <%= render 'layouts/side_menu/category' %>
    <p class="menu-label">
      More to read...
    </p>
    <%= render 'layouts/side_menu/more_read' %>
  </aside>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>R</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= javascript_tag nonce: true do -%>
    // alert('All is good')
  <% end -%>

  <%#  If you use Vue.js, I reccomend to remove turbolinks %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_pack_tag 'app_vue' %>
</head>

<body>
<%# Header %>
<%= render 'layouts/header' %>
<section class="section">
  <div class="container">
    <div class="columns">
      <%= render 'layouts/side_menu' %>
      <div class="column is-9">
        <div class="content is-medium">
          <%# ここにコンテンツを記載 %>
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render 'layouts/footer' %>
</body>

<%# 仮置き %>
<%# TODO(kkiyama117): move to js file %>
<%# font %>
<script defer src="https://kit.fontawesome.com/b76a20a8f4.js" crossorigin="anonymous"></script>
<script>
    window.addEventListener('resize', () => {
        const divs = document.querySelectorAll(".menu-list");
        if (window.innerWidth < 768) {
            divs.forEach(div => div.classList.add("tags"));
        } else {
            divs.forEach(div => div.classList.remove("tags"));
        }
    });
    document.addEventListener('DOMContentLoaded', () => {
        (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
            $notification = $delete.parentNode;
            $delete.addEventListener('click', () => {
                $notification.parentNode.removeChild($notification);
            });
        });
    });
</script>
<!-- Google absence -->
<!--<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>-->
<script>
    (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-1625817851923774",
        enable_page_level_ads: true
    });
</script>
</html>

app/views/layouts/components/_box_base.html.erb
<h3 class="title is-3"><%= yield :title %></h3>
<div class="box">
  <h4 id="const" class="title is-3"><%=yield :box_title %></h4>
  <article class="message is-primary">
                  <span class="icon has-text-primary">
                    <i class="fas fa-seedling"></i>
                  </span>
    <div class="message-body">
      <%= render yield(:renderer) %>
    </div>
  </article>
</div>

app/views/layouts/components/_main_layout.html.erb
<h3 class="title is-3">Snippets ¯\_(ツ)_/¯</h3>
<div class="box">
  <h4 id="const" class="title is-3">const</h4>
  <article class="message is-primary">
                  <span class="icon has-text-primary">
                  <i class="fab fa-js"></i>
                  </span>
    <div class="message-body">
      Block-scoped. Cannot be re-assigned. Not immutable.
    </div>
  </article>
  <pre><code class="language-javascript">const test = 'test';</code></pre>
</div>

app/views/layouts/header/_notice_and_alert.html.erb
<% if notice %>
  <div class="notification is-primary">
    <%= notice %>
    <button class="delete"></button>
  </div>
<% end %>
<% if alert %>
  <div class="notification is-danger">
    <%= alert %>
    <button class="delete"></button>
  </div>
<% end %>

app/views/layouts/side_menu/_category.html.erb
<ul class="menu-list">
  <li class="is-right">
    <%= link_to root_path, class: 'is-active' do %>
      <i class="fas fa-home"></i> HOME
    <% end %>
  </li>
  <% if current_user.present? %>
    <li class="is-right">
      <%= link_to user_path, class: 'is-active' do %>
        <i class="fas fa-user"></i> <%= current_user_name %> の設定
      <% end %>
    </li>
    <li>
      <%= link_to destroy_session_path(User), method: :delete, class: 'is-active' do %>
        <i class="fas fa-sign-out-alt"></i> <%= I18n.t('devise.shared.links.sign_out') %>
      <% end %>
    </li>
  <% else %>
    <li class="is-right">
      <%= link_to new_user_registration_path, class: 'is-active' do %>
        <i class="fas fa-user"></i> <%= I18n.t('devise.shared.links.sign_up') %>
      <% end %>
    </li>
    <li>
      <%= link_to new_session_path(User), class: 'is-active' do %>
        <i class="fas fa-sign-in-alt"></i> <%= I18n.t('devise.shared.links.sign_in') %>
      <% end %>
    </li>
  <% end %>
  <li>
    <%= link_to admin_root_path, class: 'is-active' do %>
      <i class="fas fa-tools"></i> ADMIN
    <% end %>
  </li>
  <li class="is-right">
    <%= link_to ingredients_path, class: 'is-active' do %>
      <i class="fas fa-blender-phone"></i> Recipe
    <% end %>
  </li>
</ul>

app/views/layouts/side_menu/_more_read.html.erb
<ul class="menu-list">
  <li>
      <span class="tag is-white is-medium">
        <%= link_to ingredients_path do%>
        <i class="fas fa-blender-phone"></i> Recipe
        <% end %>
      </span>
  </li>
  <li><span class="tag is-white is-medium">under construction</span></li>
</ul>